### ISSUE TITLE
POS System

### ISSUE THREAD

**Issue by kristian-bansil** [fajarghifar/inventory-management-system#14]
I want to ask why your POS is not working properly? When i am trying to use barcode scanner it scroll down only can you help me to fix this issue please?

Thank you

**Comment by fajarghifar** [comment]
I’m sorry about that. The barcode scanner feature isn’t fully functional yet. Honestly, I haven’t had the chance to explore or properly implement it because of my busy schedule and other commitments.

I appreciate your patience, and I’ll do my best to look into it as soon as I can. If you have any other issues or questions, feel free to let me know!
