### ISSUE TITLE
How to Change UI

### ISSUE THREAD

**Issue by AungPaingPhyo345** [fajarghifar/inventory-management-system#16]
how to change Dashboard UI like that? 
![image](https://github.com/user-attachments/assets/01cc8443-7f68-4759-a84c-5140c44804ff)
![image](https://github.com/user-attachments/assets/690b8a9f-f540-48e0-b074-936065210efc)

**Comment by sathishocs** [comment]
I've same question. My UI not same as screenshot. please suggest @fajarghifar

**Comment by kusman28** [comment]
I want the answer also @fajarghifar

**Comment by benmpl** [comment]
From what I've seen, at some point a PR which, among other things, fully replaced the theme. So the theme shown in Readme isn't even the same that comes with the application anymore.

**Comment by fajarghifar** [comment]
**Answer:**  

Thank you for your question, and I’d like to apologize in advance for the changes made to the UI.  

Previously, I was using **SB Admin Pro** for the UI. However, I decided to switch to a new theme, **Tabler**, due to the following reasons:  

1. **Difficulty in Customization**  
   SB Admin Pro relies on multiple third-party libraries (CSS, JS) integrated into its HTML structure. This made it challenging for me to manage the layout and identify which libraries were necessary and which weren’t.  

2. **Performance Efficiency**  
   Over time, using too many libraries could potentially make the webpage heavier, affecting its performance and loading speed.  

To address these issues, I opted to switch to a new theme, **Tabler**, which is lighter, simpler, and easier to manage in the long run.  

I hope this explanation clarifies the changes. Please feel free to ask if you have any further questions! 😊

**Comment by fajarghifar** [comment]
Thank you for your question, and I’d like to apologize in advance for the changes made to the UI.  

Previously, I was using **SB Admin Pro** for the UI. However, I decided to switch to a new theme, **Tabler**, due to the following reasons:  

1. **Difficulty in Customization**  
   SB Admin Pro relies on multiple third-party libraries (CSS, JS) integrated into its HTML structure. This made it challenging for me to manage the layout and identify which libraries were necessary and which weren’t.  

2. **Performance Efficiency**  
   Over time, using too many libraries could potentially make the webpage heavier, affecting its performance and loading speed.  

To address these issues, I opted to switch to a new theme, **Tabler**, which is lighter, simpler, and easier to manage in the long run.  

I hope this explanation clarifies the changes. Please feel free to ask if you have any further questions! 😊

**Comment by fajarghifar** [comment]
That said, it’s still possible to access the previous theme if needed. If you’d like to explore or try the previous version, you can follow these steps:  

1. **Clone the repository**  
   ```bash  
   git clone https://github.com/fajarghifar/inventory-management-system.git  
   ```  

2. **Navigate to the project directory**  
   ```bash  
   cd inventory-management-system  
   ```  

3. **Switch to the previous commit**  
   ```bash  
   git checkout 5467f24  
   ```  

By following these steps, you’ll be able to access and use the previous theme.😊
