### ISSUE TITLE
Attempt to read property "name" on null when click in product tab

### ISSUE THREAD

**Issue by bijaya012** [fajarghifar/inventory-management-system#21]
<td class="align-middle text-center">

                        {{ $product->code }}

                    </td>

                    **<td class="align-middle text-center">

                        {{ $product->category->name }}

                    </td>**

                    <td class="align-middle text-center">

                        {{ $product->quantity }}

**Comment by bijaya012** [comment]
![image](https://github.com/user-attachments/assets/0c87cb71-209a-4f35-b00f-7d7e17d99716)

**Comment by fajarghifar** [comment]
The error **"Attempt to read property 'name' on null"** happens because some products might not be linked to a category.

### Solution:
**1. Check the Relationship**  
Make sure the `Product` model includes the relationship to `Category`, like this:

```php
public function category()
{
    return $this->belongsTo(Category::class);
}
```

**2. Add a Conditional Check**  
To handle products without a category, you can add a simple conditional:

```php
<td class="align-middle text-center">
    {{ $product->category?->name ?? 'No Category' }}
</td>
```

With this approach, the error will be avoided, and you'll see "No Category" if a product doesn’t have one linked. I hope this helps, and thanks for your attention!
